Problem Statement:
Predicting Survival in the Titanic Data Set 
We will be using a decision tree to make predictions about the Titanic data set from Kaggle. This data set provides information on the Titanic passengers and can be used to predict whether a passenger survived or not. 


In [0]:
import numpy as np 
import pandas as pd 
import seaborn as sb 
import matplotlib.pyplot as plt 
import sklearn 
from pandas import Series, DataFrame 
from pylab import rcParams 
from sklearn import preprocessing 
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics 
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
Url= 'https://raw.githubusercontent.com/Nexosis/sampledata/master/titanic-train.csv'
titanic = pd.read_csv('/content/titanic-train.csv')


In [57]:
titanic.Embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [58]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Embarked  889 non-null    object 
 3   Sex       891 non-null    object 
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64  
 6   Parch     891 non-null    int64  
 7   Fare      891 non-null    float64
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [0]:
titanic.Age.fillna(titanic.Age.mean(),inplace=True)

In [60]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Embarked  889 non-null    object 
 3   Sex       891 non-null    object 
 4   Age       891 non-null    float64
 5   SibSp     891 non-null    int64  
 6   Parch     891 non-null    int64  
 7   Fare      891 non-null    float64
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [0]:
titanic.Embarked.fillna(method='ffill',inplace=True)

In [62]:
titanic.head()

Survived  Pclass Embarked     Sex   Age  SibSp  Parch     Fare
0         0       3        S    male  22.0      1      0   7.2500
1         1       1        C  female  38.0      1      0  71.2833
2         1       3        S  female  26.0      0      0   7.9250
3         1       1        S  female  35.0      1      0  53.1000
4         0       3        S    male  35.0      0      0   8.0500

In [0]:
titanic.Sex.replace(['female','male'],[0,1],inplace=True)

In [0]:
titanic = pd.get_dummies(titanic, columns=['Embarked'])

In [65]:
titanic.head()

Survived  Pclass  Sex   Age  ...     Fare  Embarked_C  Embarked_Q  Embarked_S
0         0       3    1  22.0  ...   7.2500           0           0           1
1         1       1    0  38.0  ...  71.2833           1           0           0
2         1       3    0  26.0  ...   7.9250           0           0           1
3         1       1    0  35.0  ...  53.1000           0           0           1
4         0       3    1  35.0  ...   8.0500           0           0           1

[5 rows x 10 columns]

In [0]:
y=titanic.Survived
X=titanic.drop(columns='Survived')

In [67]:
X.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_C  Embarked_Q  Embarked_S
0       3    1  22.0      1      0   7.2500           0           0           1
1       1    0  38.0      1      0  71.2833           1           0           0
2       3    0  26.0      0      0   7.9250           0           0           1
3       1    0  35.0      1      0  53.1000           0           0           1
4       3    1  35.0      0      0   8.0500           0           0           1

In [68]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [0]:
treeClassifier=DecisionTreeClassifier()

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=30)

In [0]:
model=treeClassifier.fit(X_train,y_train)

In [0]:
y_pred=model.predict(X_test)

In [73]:
confusion_matrix(y_test,y_pred)

array([[133,  27],
       [ 28,  80]])

In [74]:
accuracy_score(y_test,y_pred)

0.7947761194029851

In [75]:
model.feature_importances_

array([0.09799326, 0.32107882, 0.22630227, 0.05014005, 0.00924188,
       0.26803245, 0.00329779, 0.00666113, 0.01725233])

In [76]:
X.columns

Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked_C',
       'Embarked_Q', 'Embarked_S'],
      dtype='object')

In [0]:
X_imp=X[['Pclass', 'Sex', 'Age', 'Fare']]

In [78]:
X_imp.columns

Index(['Pclass', 'Sex', 'Age', 'Fare'], dtype='object')

In [0]:
X_imp_train, X_imp_test, y_train, y_test = train_test_split(X_imp, y, test_size=0.30, random_state=30)

In [0]:
model_imp=treeClassifier.fit(X_imp_train,y_train)

In [0]:
y_pred=model_imp.predict(X_imp_test)

In [82]:
confusion_matrix(y_test,y_pred)

array([[132,  28],
       [ 32,  76]])

In [83]:
accuracy_score(y_test,y_pred)

0.7761194029850746